name: Publish Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PUBLISH_PACKAGES_PAT: ${{ secrets.PUBLISH_PACKAGES_PAT }}
  SOURCE_IMAGE_PREFIX: mcr.microsoft.com/devcontainers
  GITHUB_USERNAME: khaitranhq

jobs:
  publish:
    name: Build and Publish images 
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: ['typescript-node:1.1.1-20-bookworm']
    steps:
      - name: authenticate Github
        run: |
          echo $PUBLISH_PACKAGES_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get image tag
        run: |
          SOURCE_IMAGE_TAG="{{ matrix.image }}"
          echo "IMAGE_TAG=${SOURCE_IMAGE_TAG}/':'/'-'" >> $GITHUB_ENV

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ env.GITHUB_USERNAME }}/devcontainer:${{ env.IMAGE_TAG }}
          build-args: |
            SOURCE_IMAGE=${{ matrix.image }}
            USER=dev
          target: app
          cache-from: type=gha
          cache-to: type=gha,mode=max
