name: Publish Images
on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  PUBLISH_PACKAGES_PAT: ${{ secrets.PUBLISH_PACKAGES_PAT }}
  SOURCE_IMAGE_PREFIX: mcr.microsoft.com/devcontainers
  GITHUB_USERNAME: khaitranhq

jobs:
  publish:
    name: Build and Publish images
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: 
          - 'typescript-node:1-20-bookworm'
          # - 'typescript-node:1-18-bookworm'
          # - 'rust:1-1-bookworm'
          # - 'cpp:1-debian12'
          # - 'javascript-node:1-20-bookworm'
          # - 'javascript-node:1-18-bookworm'
          # - 'python:1-3-bookworm'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: authenticate Github
        run: |
          echo $PUBLISH_PACKAGES_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: get image tag
        run: |
          SOURCE_IMAGE_TAG="${{ matrix.image }}"
          IMAGE_TAG=${SOURCE_IMAGE_TAG/:/-}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          USER="vscode"
          if [[ "$SOURCE_IMAGE_TAG" == *"node"* ]]; then
            USER="node"
          fi 
          echo "USER=$USER" >> $GITHUB_ENV

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.GITHUB_USERNAME }}/devcontainer:${{ env.IMAGE_TAG }}-${{ github.run_number }}
            ghcr.io/${{ env.GITHUB_USERNAME }}/devcontainer:${{ env.IMAGE_TAG }}
          build-args: |
            SOURCE_IMAGE=${{ env.SOURCE_IMAGE_PREFIX }}/${{ matrix.image }}
            USER=${{ env.USER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # remove-package:
  #   name: Remote pacakges
  #   runs-on: ubuntu-22.04
  #   steps:
      - uses: actions/delete-package-versions@v5
        with: 
          package-name: 'devcontainer'
          package-type: 'container'
          min-versions-to-keep: 10
          token: ${{ secrets.PUBLISH_PACKAGES_PAT }}
